version: '3.8'
services:
  devcontainer:
    image: fdquinones/wso2am:4.2.0
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity
    ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
      - "9763:9763"
      - "9999:9999"
      - "11111:11111"
      - "5672:5672"
      - "9711:9711"
      - "9611:9611"
      - "9099:9099"
    
