version: '3.8'
services:
  devcontainer:
    image: wso2/wso2am:4.2.0-alpine
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity
    ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
